---------------------------------------------------------------
[ 2018-07-05T10:42:29+08:00 ] 10.3.3.114 GET /dashboard/index/index
[ sql ] [ DB ] CONNECT:[ UseTime:0.004001s ] mysql:host=localhost;dbname=ipmsv3;charset=utf8
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_user` [ RunTime:0.026001s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `username` = 'b1'  AND `pwd` = 'c4ca4238a0b923820dcc509a6f75849b' LIMIT 1 [ RunTime:0.002000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.002001s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_issinfo` [ RunTime:0.003000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.002000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.002000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.002001s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_patinfo` [ RunTime:0.003000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.002000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PRO%' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_THE%' LIMIT 1 [ RunTime:0.001000s ]

---------------------------------------------------------------
[ 2018-07-05T10:42:29+08:00 ] 10.3.3.114 POST /dashboard/index/tplFile
[ sql ] [ DB ] CONNECT:[ UseTime:0.003001s ] mysql:host=localhost;dbname=ipmsv3;charset=utf8
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_user` [ RunTime:0.025001s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `username` = 'b1'  AND `pwd` = 'c4ca4238a0b923820dcc509a6f75849b' LIMIT 1 [ RunTime:0.001000s ]
---------------------------------------------------------------
[ 2018-07-05T10:42:30+08:00 ] 10.3.3.114 GET /dashboard/index/isspat2.html
[ sql ] [ DB ] CONNECT:[ UseTime:0.003000s ] mysql:host=localhost;dbname=ipmsv3;charset=utf8
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_user` [ RunTime:0.010000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `username` = 'b1'  AND `pwd` = 'c4ca4238a0b923820dcc509a6f75849b' LIMIT 1 [ RunTime:0.001001s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_issinfo` [ RunTime:0.002000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.000000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_patinfo` [ RunTime:0.002000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.001001s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001001s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001001s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('待审核')  AND `dept` = 'dept2' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('审核未通过','审核通过','变更申请','拟续费') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `issmap_type` LIKE '%_ISST_PAT%'  AND `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_patinfo` WHERE  `status` IN ('授权','续费授权')  AND `renewdeadlinedate` BETWEEN '2018-07-05 00:00:00' AND '2019-01-05 00:00:00' LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT COUNT(*) AS tp_count FROM `ipmsv3_issinfo` WHERE  `status` = '完结' LIMIT 1 [ RunTime:0.000000s ]
---------------------------------------------------------------
[ 2018-07-05T10:42:30+08:00 ] 10.3.3.114 POST /dashboard/index/issPatList
[ sql ] [ DB ] CONNECT:[ UseTime:0.003000s ] mysql:host=localhost;dbname=ipmsv3;charset=utf8
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_user` [ RunTime:0.020001s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `username` = 'b1'  AND `pwd` = 'c4ca4238a0b923820dcc509a6f75849b' LIMIT 1 [ RunTime:0.013001s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_user` WHERE  `id` = 2 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_issinfo` [ RunTime:0.003000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_issinfo` WHERE  `status` IN ('申报新增','填报','返回修改','修改完善')  AND `dept` = 'dept2'  AND `writer` = 'b1' ORDER BY `topic`  asc [ RunTime:0.001001s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_issinfo` WHERE  `status` IN ('待审核')  AND `dept` = 'dept2' ORDER BY `topic`  asc [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_issinfo` WHERE  `status` IN ('审核未通过','审核通过','变更申请','拟续费') ORDER BY `topic`  asc [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_issinfo` WHERE  `status` IN ('批准申报','申报执行','申报修改','准予变更','否决变更')  AND `executer` = 'b1'  AND `dept` = 'dept2' ORDER BY `topic`  asc [ RunTime:0.002000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_issinfo` WHERE  `status` IN ('申报复核','申报提交','续费提交','准予续费','否决申报','专利授权','专利驳回','放弃续费','续费授权','续费新增') ORDER BY `topic`  asc [ RunTime:0.001000s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `ipmsv3_patinfo` [ RunTime:0.003000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 162 LIMIT 1 [ RunTime:0.001001s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 164 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 196 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 192 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 179 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 216 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 230 LIMIT 1 [ RunTime:0.000000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 221 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 166 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SELECT * FROM `ipmsv3_patinfo` WHERE  `id` = 168 LIMIT 1 [ RunTime:0.001001s ]